/* hifi/sd-data.jsx — Story Detail data (Brasil reforestation longread). */

const SD_STORY = {
  slug: '200-trees-brasil',
  chapter: 'Brasil',
  chapterSlug: 'brasil',
  region: 'Latin America',
  tag: 'Onchain Reforestation',
  title: '200 trees planted onchain in a single weekend.',
  dek: 'How Greenpill Brasil ran a quadratic-funding round that funded reforestation across five bioregions \u2014 and what we\u2019d do differently next time.',
  author: 'Camila R.',
  authorRole: 'Steward · Greenpill Brasil',
  authorBio: 'Camila R. is a steward at Greenpill Brasil and co-organizes the S\u00e3o Paulo Web3 climate circle. She writes about coordination at the intersection of land tenure and cryptoeconomics.',
  date: 'Mar 14, 2026',
  read: '14 min read',
  heroPhoto: 'hero \u2014 atlantic forest canopy, dawn',
  translations: ['Portugu\u00eas (PT-BR)', 'Espa\u00f1ol'],
  pullQuote: 'It turns out that the hardest part of planting a tree onchain isn\u2019t the chain. It\u2019s agreeing, with people you respect, on what counts as a tree.',
  stats: [
    { n: '212',     l: 'Trees logged' },
    { n: 'R$ 41k', l: 'Funded' },
    { n: '5',       l: 'Bioregions' },
    { n: '38',      l: 'Contributors' },
  ],
  /* The article body — ordered list of typed blocks. */
  body: [
    { type: 'p',
      text: 'We started with a small question and a slightly absurd deadline. A neighbouring chapter \u2014 Greenpill C\u00f4te d\u2019Ivoire \u2014 had asked us, half in jest, how many trees we could fund onchain in a single weekend. We said two hundred. We did not, at the time, know what \u201conchain\u201d meant in this sentence.',
    },
    { type: 'p',
      text: 'Three weeks later, on a Friday evening in S\u00e3o Paulo, thirty-eight people connected wallets to a quadratic-funding round we had quietly stitched together over six video calls and one very long voice note. By Sunday night, R$ 41,000 had moved through it. By the following Wednesday, partner organisations had logged 212 trees planted across five Brazilian bioregions \u2014 each attested onchain by a steward with a phone, a GPS pin, and a small dose of patience.',
    },
    { type: 'h2', text: 'The hardest part wasn\u2019t the chain.' },
    { type: 'p',
      text: 'I want to lead with the conclusion, because the conclusion is the point.',
    },
    { type: 'pullquote', text: 'It turns out that the hardest part of planting a tree onchain isn\u2019t the chain. It\u2019s agreeing, with people you respect, on what counts as a tree.' },
    { type: 'p',
      text: 'A seedling in a vivero, three weeks before transplant? A sapling in the ground that may not survive the dry season? A mature tree that was already there and we are now committing to protect? Each of those is a defensible answer to \u201cwhat is a tree.\u201d None of them is the same answer. And the moment you put your accounting onchain, those quiet definitional disagreements become very loud.',
    },
    { type: 'p',
      text: 'We spent four of our six prep calls on this. We came out the other side with a working definition that, to be honest, is going to embarrass us in two years. But it was a definition we could defend in the open, and it let us ship.',
    },
    { type: 'h2', text: 'What we actually built' },
    { type: 'p',
      text: 'Three things, in order of how much sleep they cost:',
    },
    { type: 'list', items: [
      'A QF round with four matching pools \u2014 one per bioregion plus a small \u201cwildcard\u201d pool for first-time chapters.',
      'A lightweight attestation flow: a partner steward stands in front of a planted tree, opens a custom Farcaster frame, and signs a message that links {gps, photo, species, date} to a project ID.',
      'A public, ugly, honest dashboard that updated every hour and was the only thing anyone actually looked at.',
    ]},
    { type: 'p',
      text: 'The dashboard is what made it real. Not the chain, not the QF math, not the frame. The dashboard. Because the dashboard is where the partner organisations could see, in close to real time, that their work was being witnessed.',
    },
    { type: 'h2', text: 'Five things we\u2019d do differently' },
    { type: 'p',
      text: 'Numbered, because lists travel.',
    },
    { type: 'list', ordered: true, items: [
      'Pre-attest the trees that already exist. Half our partner orgs spent the first two days re-photographing things that have been alive for a decade. That was a misalignment of incentives we created and didn\u2019t catch until day two.',
      'Pay the stewards. We didn\u2019t. We should have. The attestation work is real work, and pretending otherwise put a quiet tax on the people we most depend on.',
      'One bioregion, not five. The five-pool design felt elegant on a whiteboard. In the field it created a sort of inter-pool comparison anxiety that nobody asked for.',
      'Defer the metric. \u201cTrees planted\u201d is legible but reductive. Survival rate at twelve months is the metric that matters. We should have committed to publishing it.',
      'Write less software. Two of the things we built could have been a Google Sheet. The fact that they weren\u2019t was a function of our enthusiasm, not the work.',
    ]},
    { type: 'h2', text: 'What\u2019s next' },
    { type: 'p',
      text: 'A second round is planned for August, in collaboration with three partner cooperatives in the Mata Atl\u00e2ntica. We\u2019re running it slower. We\u2019re paying the stewards. We\u2019re committing, in advance, to publishing the twelve-month survival numbers in 2027 \u2014 even if (especially if) they\u2019re lower than we\u2019d like.',
    },
    { type: 'p',
      text: 'If you\u2019re a chapter thinking about running something like this, two pieces of advice: start with the question of what counts, not the question of which chain. And whatever you build, build the dashboard first.',
    },
    { type: 'p',
      text: 'We will write again from the August round. Until then, the data \u2014 messy and incomplete \u2014 is public, and the partner orgs are listed below.',
    },
    { type: 'thanks', items: [
      'Inst. R\u00e9-Plantar (Mata Atl\u00e2ntica)',
      'Coletivo Cerrado Vivo (Cerrado)',
      'A.M.A. Floresta (Amaz\u00f4nia)',
      'Vale Sustent\u00e1vel (Pampa)',
      'Caatinga Comum (Caatinga)',
    ]},
  ],
};

/* "Continue reading" \u2014 three picks shown at the bottom. */
const SD_CONTINUE_READING = [
  {
    chapter: 'C\u00f4te d\u2019Ivoire', tag: 'Onchain Reforestation',
    title: 'Cocoa cooperatives, onchain',
    dek: 'A field report from Abidjan: 14 cooperatives, 1 attestation flow.',
    author: 'A\u00efcha K.', date: 'Dec 2025', read: '10 min',
    photo: 'thumb \u2014 abidjan cooperative',
  },
  {
    chapter: 'Kenya', tag: 'Public Goods',
    title: 'Grassroots Economics, six months in',
    dek: 'What we learned running community currencies in Mukuru.',
    author: 'David O.', date: 'Mar 2026', read: '8 min',
    photo: 'thumb \u2014 mukuru market',
  },
  {
    chapter: 'Brasil', tag: 'Public Goods',
    title: 'What a small QF round taught us about consensus',
    dek: 'A $4k round funded twelve projects \u2014 and surfaced disagreements no spreadsheet could.',
    author: 'Rafa S.', date: 'Dec 2025', read: '9 min',
    photo: 'thumb \u2014 qf round',
  },
];

Object.assign(window, { SD_STORY, SD_CONTINUE_READING });
